v = int(input("Digite um numero para ver sua tabuada: "))
print("-" * 12)
print("{} X {} = {}".format(v, 1, v * 1))
print("{} X {} = {}".format(v, 2, v * 2))
print("{} X {} = {}".format(v, 3, v * 3))
print("{} X {} = {}".format(v, 4, v * 4))
print("{} X {} = {}".format(v, 5, v * 5))
print("{} X {} = {}".format(v, 6, v * 6))
print("{} X {} = {}".format(v, 7, v * 7))
print("{} X {} = {}".format(v, 8, v * 8))
print("{} X {} = {}".format(v, 9, v * 9))
print("{} X {} = {}".format(v, 10, v * 10))
print("-" * 12)